squared_numbers = [x**2 for x in range(10)]
print(squared_numbers)

odds = list(filter(lambda x: x % 2 != 0, range(10)))
# filter(): A higher-order function that takes a function and an iterable, returning only the items where the function evaluates to True
print(odds)

sentence = ' '.join(['Python', 'is', 'fun'])
print(sentence)

num_sum = sum(range(1, 101))
print(num_sum)

first_odd = next(x for x in range(20) if x % 2 != 0)
# next(): This retrieves the very first item generated by the expression and stops. Because it is lazy, Python stops processing the moment it finds the first odd number (1), making this highly performance efficient for large datasets.
print(first_odd)